/** @module plugins
 * Main public API for the daemon plugin module.
 * Re-exports the stable plugin surface from concern barrels only; external
 * daemon runtime code should import plugins through this root barrel.
 */
export {
  RESTRICTED_DEFAULT_CAPABILITIES,
  TRUSTED_DEFAULT_CAPABILITIES,
  UntilSyntaxError,
  __resetPluginEventBufferForTests,
  buildConnectorProbe,
  checkConnectorTokenIssuance,
  countSnapshotsForProject,
  createSnapshot,
  defaultCapabilities,
  defaultRegistryRoots,
  defaultTrustForRecord,
  deleteInstalledPlugin,
  deriveAutoOAuthPrompts,
  ensureCoreQualityStages,
  evaluateUntil,
  getInstalledPlugin,
  getManifestContextCraft,
  getPluginContextCraft,
  getSnapshot,
  getSnapshotContextCraft,
  grantCapabilities,
  isParseableUntil,
  linkSnapshotToConversation,
  linkSnapshotToProject,
  linkSnapshotToRun,
  listInstalledPlugins,
  listSnapshotsForProject,
  markSnapshotStale,
  mergeAutoOAuthPrompts,
  migratePlugins,
  parseUntil,
  pluginEventBufferSize,
  pluginEventSnapshot,
  pruneExpiredSnapshots,
  purgePluginEventBuffer,
  recordPluginEvent,
  registryRootsForDataDir,
  requiredCapabilities,
  resolveCapabilitiesGranted,
  resolveConnectorBindings,
  resolvePluginFolder,
  restoreProjectSnapshotLink,
  revokeCapabilities,
  rowToInstalledPlugin,
  rowToSnapshot,
  subscribePluginEvents,
  summarisePluginEvents,
  upsertInstalledPlugin,
  validateCapabilityList,
  validateConnectorRefs,
} from './core/index.js';
export type {
  ConnectorCatalogEntry,
  ConnectorGateStatus,
  ConnectorProbe,
  ConnectorRefValidationIssue,
  CreateSnapshotInput,
  EnsureCoreStagesInput,
  EvaluationResult,
  InvalidCapabilityIssue,
  PluginEvent,
  PluginEventKind,
  PluginEventStats,
  PruneExpiredOptions,
  PruneExpiredResult,
  PurgePluginEventBufferResult,
  RegistryRoots,
  ResolveFailure,
  ResolveOptions,
  ResolveOutcome,
  ResolveResult,
  ScannedPlugin,
  SignalKind,
  UntilComparison,
  UntilExpression,
  UntilOp,
  UntilSignals,
} from './core/index.js';

export {
  FIRST_PARTY_ATOMS,
  PERMISSIVE_DEFAULT_SIGNALS,
  applyDiffReviewDecisionToCwd,
  applyPatchForStep,
  clearAtomWorkers,
  deriveAutoAtomSurfaces,
  findAtom,
  getAtomWorker,
  isDeployableAppEligible,
  isDiffReviewSurfaceId,
  isImplementedAtom,
  isKnownAtom,
  liftTokens,
  listRegisteredAtomIds,
  loadAtomBodies,
  parseDesignSystemTokens,
  parseDiffReviewGenuiResponse,
  pickSolidColor,
  readPlanProgress,
  recordHandoff,
  registerAtomWorker,
  registerBuiltInAtomWorkers,
  resetBuiltInAtomWorkersForTests,
  runAndPersistHandoff,
  runBuildTest,
  runCodeImport,
  runDesignExtract,
  runDiffReview,
  runFigmaExtract,
  runHandoffAtom,
  runRewritePlan,
  runStageWithRegistry,
  runTokenMap,
  skipStep,
  unregisterAtomWorker,
  walkNode,
  writeBuildTestReport,
} from './atoms/index.js';
export type {
  ApplyDiffReviewDecisionFailure,
  ApplyDiffReviewDecisionInput,
  ApplyDiffReviewDecisionResult,
  ApplyPatchInput,
  ApplyPatchResult,
  AtomCatalogEntry,
  AtomOutcome,
  AtomStatus,
  AtomWorker,
  AtomWorkerContext,
  AtomBodyEntry,
  AutoAtomSurfaceContext,
  BuildTestCommandResult,
  BuildTestReport,
  BuildTestRunOptions,
  BuildTestStatus,
  CodeImportFileEntry,
  CodeImportIndex,
  CodeImportRunOptions,
  CodeImportSkipped,
  DesignExtractOptions,
  DesignExtractReport,
  DesignSystemToken,
  DesignSystemTokenBag,
  DesignTokenEntry,
  DesignTokenKind,
  DiffReviewDecision,
  DiffReviewDecisionFile,
  DiffReviewMeta,
  DiffReviewOptions,
  DiffReviewReport,
  DiffReviewer,
  FigmaApiNode,
  FigmaExtractOptions,
  FigmaExtractReport,
  FigmaNode,
  OwnershipEntry,
  OwnershipTier,
  ParsedDiffReviewDecision,
  PatchReceiptEntry,
  PatchStepRecord,
  PatchStepStatus,
  RecordHandoffInput,
  RecordHandoffResult,
  RewritePlanOptions,
  RewritePlanReport,
  RewriteStep,
  RunAndPersistHandoffInput,
  RunAndPersistHandoffResult,
  RunHandoffAtomInput,
  RunHandoffAtomResult,
  SkipStepInput,
  StageRegistryOutcome,
  TokenMapMatch,
  TokenMapOptions,
  TokenMapReport,
  TokenMapUnmatched,
} from './atoms/index.js';

export {
  addMarketplace,
  buildRegistryViewFromManifest,
  createPluginRegistryView,
  defaultBundledRoot,
  diffPlugins,
  doctorMarketplace,
  doctorPlugin,
  ensureMarketplaceManifest,
  flattenValidationDiagnostics,
  getMarketplace,
  listMarketplaces,
  markStaleSnapshotsForProject,
  marketplaceManifestUrlForRegistry,
  marketplaceRegistryBaseUrl,
  marketplaceRegistryIdFromUrl,
  pluginInventoryStats,
  pluginSourceBuckets,
  refreshMarketplace,
  registerBundledPlugins,
  removeMarketplace,
  resolveMarketplaceFetchUrl,
  resolvePluginInMarketplaces,
  searchInstalledPlugins,
  setMarketplaceTrust,
  snapshotInventoryStats,
  summarizeDoctor,
  validatePluginFolder,
} from './catalog/index.js';
export type {
  AddMarketplaceFailure,
  AddMarketplaceInput,
  AddMarketplaceResult,
  Diagnostic,
  DiagnosticSeverity,
  DiffPluginsInput,
  DoctorReport,
  EnsureMarketplaceManifestInput,
  MarketplaceDoctorInput,
  MarketplaceRow,
  MarketplaceTrustTier,
  PluginDiffEntry,
  PluginDiffReport,
  PluginInventoryStats,
  PluginSourceBucket,
  PluginSourceBucketsResult,
  RefreshMarketplaceResult,
  RegisterBundledPluginsInput,
  RegisterBundledPluginsResult,
  ResolvedPluginEntry,
  SearchInstalledPluginsInput,
  SearchInstalledPluginsResult,
  SearchInstalledPluginsResultEntry,
  SnapshotInventoryStats,
  SnapshotStatsRow,
  ValidatePluginFolderInput,
  ValidatePluginFolderResult,
} from './catalog/index.js';

export {
  PUBLISH_TARGETS,
  PackPluginError,
  PluginDuplicateProjectError,
  PublishError,
  ScaffoldError,
  buildMarketplaceJsonEntry,
  buildPublishLink,
  defaultPluginLockfile,
  detectSkillPluginCandidate,
  dismissSkillPluginCandidate,
  duplicatePluginExampleIntoProject,
  generateSkillPluginDraft,
  getSkillPluginCandidate,
  insertSkillPluginCandidate,
  installFromLocalFolder,
  installPlugin,
  listSkillPluginCandidates,
  lockEntryFromInstalled,
  packPlugin,
  readPluginLockfile,
  scaffoldPlugin,
  uninstallPlugin,
  upsertMarketplaceJsonEntry,
  upsertPluginLockfileEntry,
  writePluginLockfile,
} from './install/index.js';
export type {
  ArchiveFetcher,
  DetectSkillPluginCandidateInput,
  DuplicatePluginExampleInput,
  DuplicatePluginExampleResult,
  InstallErrorEvent,
  InstallEvent,
  InstallOptions,
  InstallProgressEvent,
  InstallSuccessEvent,
  MarketplaceJsonEntry,
  MarketplaceJsonManifest,
  MarketplaceJsonPublishOutcome,
  PackPluginInput,
  PackPluginResult,
  PluginLockEntry,
  PluginLockfile,
  PluginSourceKind,
  PublishCatalog,
  PublishLink,
  PublishMetadata,
  ScaffoldInput,
  ScaffoldResult,
  SkillPluginDraftGenerationResult,
  UninstallResult,
} from './install/index.js';

export {
  ExportError,
  MissingInputError,
  PipelineConfigError,
  applyPlugin,
  capabilitiesRequiredError,
  diffSnapshots,
  exportPlugin,
  listIterationsForRun,
  loadPluginLocalSkill,
  parseSignalKv,
  pickFirstLocalSkillPath,
  pluginPromptBlock,
  recordIteration,
  resolvePluginSnapshot,
  runPipeline,
  runPipelineForRun,
  simulatePipeline,
  startSnapshotGc,
  verifyPlugin,
} from './runtime/index.js';
export type {
  ApplyComputed,
  ApplyInput,
  ApplyTrust,
  DevloopIterationRow,
  DiffSnapshotsInput,
  ExportInput,
  ExportResult,
  ExportTarget,
  McpServerSpec,
  PipelineEnv,
  PipelineEventSink,
  PipelineRunnerInput,
  PluginConnectorBinding,
  PluginLocalSkill,
  ResolveSnapshotError,
  ResolveSnapshotInput,
  ResolveSnapshotOk,
  ResolveSnapshotResult,
  RunPipelineInput,
  SimulatePipelineInput,
  SimulatePipelineResult,
  SimulateStageOutcome,
  SnapshotDiffEntry,
  SnapshotDiffReport,
  SnapshotGcHandle,
  SnapshotGcOptions,
  StageOutcomeRecord,
  StageRunOutcome,
  StageRunner,
  StageSignalProvider,
  VerifyCheckId,
  VerifyCheckOutcome,
  VerifyConfig,
  VerifyInput,
  VerifyReport,
} from './runtime/index.js';

export {
  AssetCacheError,
  CACHEABLE_MEDIA_EXT,
  assertSafePublicUrl,
  assetCacheKey,
  assetCacheRewriteUrl,
  createPluginAssetCache,
  createValidatingLookup,
  isCacheableExternalUrl,
  isPrivateAddress,
} from './assets/index.js';
export type { AssetCacheResult, PluginAssetCache, PluginAssetCacheOptions } from './assets/index.js';

export {
  PLUGIN_PREVIEWS_ROUTE,
  applyBakedPreviews,
  bakedPreviewBlock,
  resolvePluginPreviewsDir,
} from './previews/index.js';
export type { BakedPreviewBlock } from './previews/index.js';

export {
  PLUGIN_SHARE_ACTION_LABELS,
  USER_PLUGIN_SOURCE_KINDS,
  __forTestReadProjectPluginManifest,
  copyPluginFolderForProjectContext,
  githubRepoNameFromPluginName,
  normalizePluginShareAction,
  renderPluginSharePrompt,
} from './sharing/index.js';
